import { queryOptions } from '@tanstack/react-query'
import type {
  CourseData,
  CourseSummary,
  CourseWordEntry,
  Deck,
  DeckSummary,
  Dialogue,
  DialogueSummary,
  GrammarTopic,
  GrammarTopicSummary,
  SentencePack,
  SentencePackSummary,
  Track,
} from './types'

// Static JSON on Vercel's CDN for now. Swap these URLs for /api/* serverless
// functions when decks move into a database.
async function fetchJson<T>(url: string): Promise<T> {
  const res = await fetch(url)
  if (!res.ok) throw new Error(`Không tải được ${url} (${res.status})`)
  return res.json() as Promise<T>
}

/** Topic decks (the catalog never lists course lessons, so every entry has a track). */
export type TopicDeckSummary = DeckSummary & { track: Track }

export const catalogQuery = queryOptions({
  queryKey: ['catalog'],
  queryFn: () => fetchJson<TopicDeckSummary[]>('/decks/index.json'),
})

export const deckQuery = (deckId: string) =>
  queryOptions({
    queryKey: ['deck', deckId],
    queryFn: () => fetchJson<Deck>(`/decks/${encodeURIComponent(deckId)}.json`),
  })

/** Several decks at once (review sets); decks that no longer exist are skipped. */
export const decksQuery = (deckIds: string[]) =>
  queryOptions({
    queryKey: ['decks', deckIds],
    queryFn: async () => {
      const results = await Promise.allSettled(
        deckIds.map((id) => fetchJson<Deck>(`/decks/${encodeURIComponent(id)}.json`)),
      )
      return results.flatMap((r) => (r.status === 'fulfilled' ? [r.value] : []))
    },
  })

/** Courses are optional content (generated by scripts/vocab); a missing index means none yet. */
export const coursesQuery = queryOptions({
  queryKey: ['courses'],
  queryFn: async () => {
    const res = await fetch('/courses/index.json')
    const type = res.headers.get('content-type') ?? ''
    return res.ok && type.includes('json') ? ((await res.json()) as CourseSummary[]) : []
  },
})

/** Every word of a course (~3,000), including lessons whose content isn't generated yet. */
export const courseWordsQuery = (courseId: string) =>
  queryOptions({
    queryKey: ['course-words', courseId],
    queryFn: () => fetchJson<CourseWordEntry[]>(`/courses/${encodeURIComponent(courseId)}.words.json`),
    staleTime: Infinity,
  })

export const courseQuery = (courseId: string) =>
  queryOptions({
    queryKey: ['course', courseId],
    queryFn: () => fetchJson<CourseData>(`/courses/${encodeURIComponent(courseId)}.json`),
  })

export const grammarIndexQuery = queryOptions({
  queryKey: ['grammar'],
  queryFn: () => fetchJson<GrammarTopicSummary[]>('/grammar/index.json'),
})

export const grammarTopicQuery = (topicId: string) =>
  queryOptions({
    queryKey: ['grammar', topicId],
    queryFn: () => fetchJson<GrammarTopic>(`/grammar/${encodeURIComponent(topicId)}.json`),
  })

export const sentencePacksQuery = queryOptions({
  queryKey: ['sentences'],
  queryFn: () => fetchJson<SentencePackSummary[]>('/sentences/index.json'),
  staleTime: Infinity,
})

export const sentencePackQuery = (packId: string) =>
  queryOptions({
    queryKey: ['sentences', packId],
    queryFn: () => fetchJson<SentencePack>(`/sentences/${encodeURIComponent(packId)}.json`),
    staleTime: Infinity,
  })

export const dialoguesQuery = queryOptions({
  queryKey: ['talk'],
  queryFn: () => fetchJson<DialogueSummary[]>('/talk/index.json'),
})

export const dialogueQuery = (dialogueId: string) =>
  queryOptions({
    queryKey: ['talk', dialogueId],
    queryFn: () => fetchJson<Dialogue>(`/talk/${encodeURIComponent(dialogueId)}.json`),
  })
