import { queryOptions } from '@tanstack/react-query'
import type { CourseData, CourseSummary, Deck, DeckSummary } from './types'

// Static JSON on Vercel's CDN for now. Swap these URLs for /api/* serverless
// functions when decks move into a database.
async function fetchJson<T>(url: string): Promise<T> {
  const res = await fetch(url)
  if (!res.ok) throw new Error(`Không tải được ${url} (${res.status})`)
  return res.json() as Promise<T>
}

export const catalogQuery = queryOptions({
  queryKey: ['catalog'],
  queryFn: () => fetchJson<DeckSummary[]>('/decks/index.json'),
})

export const deckQuery = (deckId: string) =>
  queryOptions({
    queryKey: ['deck', deckId],
    queryFn: () => fetchJson<Deck>(`/decks/${encodeURIComponent(deckId)}.json`),
  })

/** Courses are optional content (generated by scripts/vocab); a missing index means none yet. */
export const coursesQuery = queryOptions({
  queryKey: ['courses'],
  queryFn: async () => {
    const res = await fetch('/courses/index.json')
    const type = res.headers.get('content-type') ?? ''
    return res.ok && type.includes('json') ? ((await res.json()) as CourseSummary[]) : []
  },
})

export const courseQuery = (courseId: string) =>
  queryOptions({
    queryKey: ['course', courseId],
    queryFn: () => fetchJson<CourseData>(`/courses/${encodeURIComponent(courseId)}.json`),
  })
