// Validates every deck and generates public/decks/index.json (the deck catalog).
// Fails the build if a deck is missing data one of the games needs, or if a
// language lacks a track, so every language always gets the same games.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const LANGS = ['en', 'ja', 'zh']
const TRACKS = ['kids', 'work', 'exam']
const MIN_WORDS = 6 // Match uses 6 pairs
const MIN_SENTENCES = 3 // Sentence builder + dictation

const KANA = /^[\p{Script=Hiragana}\p{Script=Katakana}ー]+$/u
const LATIN = /^[\p{Script=Latin}\s'’-]+$/u

const dir = join(import.meta.dirname, '..', 'public', 'decks')
const errors = []

const decks = readdirSync(dir)
  .filter((f) => f.endsWith('.json') && f !== 'index.json')
  .map((f) => {
    const deck = JSON.parse(readFileSync(join(dir, f), 'utf8'))
    const fail = (msg) => errors.push(`${f}: ${msg}`)

    if (`${deck.id}.json` !== f) fail(`id "${deck.id}" must match the file name`)
    if (!LANGS.includes(deck.lang)) fail(`unknown lang "${deck.lang}"`)
    // Course lessons (generated by scripts/vocab) belong to a course instead of a track.
    if (deck.course) {
      if (!Number.isInteger(deck.lesson)) fail('course lessons need a numeric "lesson"')
    } else if (!TRACKS.includes(deck.track)) fail(`unknown track "${deck.track}"`)
    for (const key of ['level', 'title', 'description']) if (!deck[key]) fail(`missing "${key}"`)

    if (deck.words.length < MIN_WORDS) fail(`needs at least ${MIN_WORDS} words (has ${deck.words.length})`)
    if (deck.sentences.length < MIN_SENTENCES) fail(`needs at least ${MIN_SENTENCES} sentences`)

    const seen = new Set()
    for (const w of deck.words) {
      if (!w.id || !w.term || !w.meaning) fail(`word ${JSON.stringify(w.id ?? w.term)} needs id, term and meaning`)
      if (!w.example || !w.exampleMeaning)
        fail(`word "${w.id}" needs an example and its exampleMeaning (Nghe hiểu, Điền từ)`)
      if (seen.has(w.id)) fail(`duplicate word id "${w.id}"`)
      seen.add(w.id)
    }
    for (const s of deck.sentences) {
      if (!s.tokens?.length || !s.meaning) fail(`sentence "${s.id}" needs tokens and meaning`)
      if (deck.lang === 'ja' && !KANA.test(s.reading ?? ''))
        fail(`sentence "${s.id}" needs a kana-only "reading" (used for kana/romaji answers)`)
      if (deck.lang === 'zh' && !LATIN.test(s.reading ?? ''))
        fail(`sentence "${s.id}" needs a pinyin "reading" (used for pinyin answers)`)
    }

    const { words, sentences, ...summary } = deck
    return { ...summary, wordCount: words.length, sentenceCount: sentences.length }
  })
  .sort((a, b) => a.id.localeCompare(b.id))

// Only topic decks go in the catalog; course lessons are listed in public/courses/.
const catalog = decks.filter((d) => !d.course)

for (const lang of LANGS)
  for (const track of TRACKS)
    if (!catalog.some((d) => d.lang === lang && d.track === track)) errors.push(`no "${track}" deck for "${lang}"`)

if (errors.length) {
  console.error(`✗ Deck validation failed:\n  ${errors.join('\n  ')}`)
  process.exit(1)
}

writeFileSync(join(dir, 'index.json'), JSON.stringify(catalog, null, 2) + '\n')
console.log(
  `catalog: ${catalog.length} topic decks + ${decks.length - catalog.length} course lessons, ${LANGS.length} languages × ${TRACKS.length} tracks ✓`,
)
