/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IdiomsRouteImport } from './routes/idioms'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CoursesCourseIdRouteImport } from './routes/courses/$courseId'
import { Route as DecksDeckIdRouteRouteImport } from './routes/decks/$deckId/route'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as GamesGameIdRouteImport } from './routes/games/$gameId'
import { Route as GrammarIndexRouteImport } from './routes/grammar/index'
import { Route as GrammarTopicIdRouteImport } from './routes/grammar/$topicId'
import { Route as PlayIndexRouteImport } from './routes/play/index'
import { Route as PlayCodeRouteImport } from './routes/play/$code'
import { Route as SentencesIndexRouteImport } from './routes/sentences/index'
import { Route as SentencesPackIdRouteImport } from './routes/sentences/$packId'
import { Route as TalkIndexRouteImport } from './routes/talk/index'
import { Route as TalkDialogueIdRouteImport } from './routes/talk/$dialogueId'
import { Route as DecksDeckIdIndexRouteImport } from './routes/decks/$deckId/index'
import { Route as DecksDeckIdClozeRouteImport } from './routes/decks/$deckId/cloze'
import { Route as DecksDeckIdDictationRouteImport } from './routes/decks/$deckId/dictation'
import { Route as DecksDeckIdFlashcardRouteImport } from './routes/decks/$deckId/flashcard'
import { Route as DecksDeckIdListenRouteImport } from './routes/decks/$deckId/listen'
import { Route as DecksDeckIdMatchRouteImport } from './routes/decks/$deckId/match'
import { Route as DecksDeckIdQuizRouteImport } from './routes/decks/$deckId/quiz'
import { Route as DecksDeckIdSentenceRouteImport } from './routes/decks/$deckId/sentence'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IdiomsRoute = IdiomsRouteImport.update({
  id: '/idioms',
  path: '/idioms',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksDeckIdRouteRoute = DecksDeckIdRouteRouteImport.update({
  id: '/decks/$deckId',
  path: '/decks/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarIndexRoute = GrammarIndexRouteImport.update({
  id: '/grammar/',
  path: '/grammar/',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarTopicIdRoute = GrammarTopicIdRouteImport.update({
  id: '/grammar/$topicId',
  path: '/grammar/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayCodeRoute = PlayCodeRouteImport.update({
  id: '/play/$code',
  path: '/play/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const SentencesIndexRoute = SentencesIndexRouteImport.update({
  id: '/sentences/',
  path: '/sentences/',
  getParentRoute: () => rootRouteImport,
} as any)
const SentencesPackIdRoute = SentencesPackIdRouteImport.update({
  id: '/sentences/$packId',
  path: '/sentences/$packId',
  getParentRoute: () => rootRouteImport,
} as any)
const TalkIndexRoute = TalkIndexRouteImport.update({
  id: '/talk/',
  path: '/talk/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalkDialogueIdRoute = TalkDialogueIdRouteImport.update({
  id: '/talk/$dialogueId',
  path: '/talk/$dialogueId',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksDeckIdIndexRoute = DecksDeckIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DecksDeckIdRouteRoute,
} as any)
const DecksDeckIdClozeRoute = DecksDeckIdClozeRouteImport.update({
  id: '/cloze',
  path: '/cloze',
  getParentRoute: () => DecksDeckIdRouteRoute,
} as any)
const DecksDeckIdDictationRoute = DecksDeckIdDictationRouteImport.update({
  id: '/dictation',
  path: '/dictation',
  getParentRoute: () => DecksDeckIdRouteRoute,
} as any)
const DecksDeckIdFlashcardRoute = DecksDeckIdFlashcardRouteImport.update({
  id: '/flashcard',
  path: '/flashcard',
  getParentRoute: () => DecksDeckIdRouteRoute,
} as any)
const DecksDeckIdListenRoute = DecksDeckIdListenRouteImport.update({
  id: '/listen',
  path: '/listen',
  getParentRoute: () => DecksDeckIdRouteRoute,
} as any)
const DecksDeckIdMatchRoute = DecksDeckIdMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => DecksDeckIdRouteRoute,
} as any)
const DecksDeckIdQuizRoute = DecksDeckIdQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => DecksDeckIdRouteRoute,
} as any)
const DecksDeckIdSentenceRoute = DecksDeckIdSentenceRouteImport.update({
  id: '/sentence',
  path: '/sentence',
  getParentRoute: () => DecksDeckIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/docs': typeof DocsRoute
  '/idioms': typeof IdiomsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/decks/$deckId': typeof DecksDeckIdRouteRouteWithChildren
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/grammar/$topicId': typeof GrammarTopicIdRoute
  '/play/$code': typeof PlayCodeRoute
  '/sentences/$packId': typeof SentencesPackIdRoute
  '/talk/$dialogueId': typeof TalkDialogueIdRoute
  '/games/': typeof GamesIndexRoute
  '/grammar/': typeof GrammarIndexRoute
  '/play/': typeof PlayIndexRoute
  '/sentences/': typeof SentencesIndexRoute
  '/talk/': typeof TalkIndexRoute
  '/decks/$deckId/cloze': typeof DecksDeckIdClozeRoute
  '/decks/$deckId/dictation': typeof DecksDeckIdDictationRoute
  '/decks/$deckId/flashcard': typeof DecksDeckIdFlashcardRoute
  '/decks/$deckId/listen': typeof DecksDeckIdListenRoute
  '/decks/$deckId/match': typeof DecksDeckIdMatchRoute
  '/decks/$deckId/quiz': typeof DecksDeckIdQuizRoute
  '/decks/$deckId/sentence': typeof DecksDeckIdSentenceRoute
  '/decks/$deckId/': typeof DecksDeckIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/docs': typeof DocsRoute
  '/idioms': typeof IdiomsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/grammar/$topicId': typeof GrammarTopicIdRoute
  '/play/$code': typeof PlayCodeRoute
  '/sentences/$packId': typeof SentencesPackIdRoute
  '/talk/$dialogueId': typeof TalkDialogueIdRoute
  '/games': typeof GamesIndexRoute
  '/grammar': typeof GrammarIndexRoute
  '/play': typeof PlayIndexRoute
  '/sentences': typeof SentencesIndexRoute
  '/talk': typeof TalkIndexRoute
  '/decks/$deckId/cloze': typeof DecksDeckIdClozeRoute
  '/decks/$deckId/dictation': typeof DecksDeckIdDictationRoute
  '/decks/$deckId/flashcard': typeof DecksDeckIdFlashcardRoute
  '/decks/$deckId/listen': typeof DecksDeckIdListenRoute
  '/decks/$deckId/match': typeof DecksDeckIdMatchRoute
  '/decks/$deckId/quiz': typeof DecksDeckIdQuizRoute
  '/decks/$deckId/sentence': typeof DecksDeckIdSentenceRoute
  '/decks/$deckId': typeof DecksDeckIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/docs': typeof DocsRoute
  '/idioms': typeof IdiomsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/decks/$deckId': typeof DecksDeckIdRouteRouteWithChildren
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/grammar/$topicId': typeof GrammarTopicIdRoute
  '/play/$code': typeof PlayCodeRoute
  '/sentences/$packId': typeof SentencesPackIdRoute
  '/talk/$dialogueId': typeof TalkDialogueIdRoute
  '/games/': typeof GamesIndexRoute
  '/grammar/': typeof GrammarIndexRoute
  '/play/': typeof PlayIndexRoute
  '/sentences/': typeof SentencesIndexRoute
  '/talk/': typeof TalkIndexRoute
  '/decks/$deckId/cloze': typeof DecksDeckIdClozeRoute
  '/decks/$deckId/dictation': typeof DecksDeckIdDictationRoute
  '/decks/$deckId/flashcard': typeof DecksDeckIdFlashcardRoute
  '/decks/$deckId/listen': typeof DecksDeckIdListenRoute
  '/decks/$deckId/match': typeof DecksDeckIdMatchRoute
  '/decks/$deckId/quiz': typeof DecksDeckIdQuizRoute
  '/decks/$deckId/sentence': typeof DecksDeckIdSentenceRoute
  '/decks/$deckId/': typeof DecksDeckIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/docs'
    | '/idioms'
    | '/leaderboard'
    | '/review'
    | '/settings'
    | '/decks/$deckId'
    | '/courses/$courseId'
    | '/games/$gameId'
    | '/grammar/$topicId'
    | '/play/$code'
    | '/sentences/$packId'
    | '/talk/$dialogueId'
    | '/games/'
    | '/grammar/'
    | '/play/'
    | '/sentences/'
    | '/talk/'
    | '/decks/$deckId/cloze'
    | '/decks/$deckId/dictation'
    | '/decks/$deckId/flashcard'
    | '/decks/$deckId/listen'
    | '/decks/$deckId/match'
    | '/decks/$deckId/quiz'
    | '/decks/$deckId/sentence'
    | '/decks/$deckId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/docs'
    | '/idioms'
    | '/leaderboard'
    | '/review'
    | '/settings'
    | '/courses/$courseId'
    | '/games/$gameId'
    | '/grammar/$topicId'
    | '/play/$code'
    | '/sentences/$packId'
    | '/talk/$dialogueId'
    | '/games'
    | '/grammar'
    | '/play'
    | '/sentences'
    | '/talk'
    | '/decks/$deckId/cloze'
    | '/decks/$deckId/dictation'
    | '/decks/$deckId/flashcard'
    | '/decks/$deckId/listen'
    | '/decks/$deckId/match'
    | '/decks/$deckId/quiz'
    | '/decks/$deckId/sentence'
    | '/decks/$deckId'
  id:
    | '__root__'
    | '/'
    | '/community'
    | '/docs'
    | '/idioms'
    | '/leaderboard'
    | '/review'
    | '/settings'
    | '/decks/$deckId'
    | '/courses/$courseId'
    | '/games/$gameId'
    | '/grammar/$topicId'
    | '/play/$code'
    | '/sentences/$packId'
    | '/talk/$dialogueId'
    | '/games/'
    | '/grammar/'
    | '/play/'
    | '/sentences/'
    | '/talk/'
    | '/decks/$deckId/cloze'
    | '/decks/$deckId/dictation'
    | '/decks/$deckId/flashcard'
    | '/decks/$deckId/listen'
    | '/decks/$deckId/match'
    | '/decks/$deckId/quiz'
    | '/decks/$deckId/sentence'
    | '/decks/$deckId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityRoute: typeof CommunityRoute
  DocsRoute: typeof DocsRoute
  IdiomsRoute: typeof IdiomsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
  DecksDeckIdRouteRoute: typeof DecksDeckIdRouteRouteWithChildren
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  GamesGameIdRoute: typeof GamesGameIdRoute
  GrammarTopicIdRoute: typeof GrammarTopicIdRoute
  PlayCodeRoute: typeof PlayCodeRoute
  SentencesPackIdRoute: typeof SentencesPackIdRoute
  TalkDialogueIdRoute: typeof TalkDialogueIdRoute
  GamesIndexRoute: typeof GamesIndexRoute
  GrammarIndexRoute: typeof GrammarIndexRoute
  PlayIndexRoute: typeof PlayIndexRoute
  SentencesIndexRoute: typeof SentencesIndexRoute
  TalkIndexRoute: typeof TalkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idioms': {
      id: '/idioms'
      path: '/idioms'
      fullPath: '/idioms'
      preLoaderRoute: typeof IdiomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckId': {
      id: '/decks/$deckId'
      path: '/decks/$deckId'
      fullPath: '/decks/$deckId'
      preLoaderRoute: typeof DecksDeckIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar/': {
      id: '/grammar/'
      path: '/grammar'
      fullPath: '/grammar/'
      preLoaderRoute: typeof GrammarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar/$topicId': {
      id: '/grammar/$topicId'
      path: '/grammar/$topicId'
      fullPath: '/grammar/$topicId'
      preLoaderRoute: typeof GrammarTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/': {
      id: '/play/'
      path: '/play'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$code': {
      id: '/play/$code'
      path: '/play/$code'
      fullPath: '/play/$code'
      preLoaderRoute: typeof PlayCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentences/': {
      id: '/sentences/'
      path: '/sentences'
      fullPath: '/sentences/'
      preLoaderRoute: typeof SentencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentences/$packId': {
      id: '/sentences/$packId'
      path: '/sentences/$packId'
      fullPath: '/sentences/$packId'
      preLoaderRoute: typeof SentencesPackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talk/': {
      id: '/talk/'
      path: '/talk'
      fullPath: '/talk/'
      preLoaderRoute: typeof TalkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talk/$dialogueId': {
      id: '/talk/$dialogueId'
      path: '/talk/$dialogueId'
      fullPath: '/talk/$dialogueId'
      preLoaderRoute: typeof TalkDialogueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckId/': {
      id: '/decks/$deckId/'
      path: '/'
      fullPath: '/decks/$deckId/'
      preLoaderRoute: typeof DecksDeckIdIndexRouteImport
      parentRoute: typeof DecksDeckIdRouteRoute
    }
    '/decks/$deckId/cloze': {
      id: '/decks/$deckId/cloze'
      path: '/cloze'
      fullPath: '/decks/$deckId/cloze'
      preLoaderRoute: typeof DecksDeckIdClozeRouteImport
      parentRoute: typeof DecksDeckIdRouteRoute
    }
    '/decks/$deckId/dictation': {
      id: '/decks/$deckId/dictation'
      path: '/dictation'
      fullPath: '/decks/$deckId/dictation'
      preLoaderRoute: typeof DecksDeckIdDictationRouteImport
      parentRoute: typeof DecksDeckIdRouteRoute
    }
    '/decks/$deckId/flashcard': {
      id: '/decks/$deckId/flashcard'
      path: '/flashcard'
      fullPath: '/decks/$deckId/flashcard'
      preLoaderRoute: typeof DecksDeckIdFlashcardRouteImport
      parentRoute: typeof DecksDeckIdRouteRoute
    }
    '/decks/$deckId/listen': {
      id: '/decks/$deckId/listen'
      path: '/listen'
      fullPath: '/decks/$deckId/listen'
      preLoaderRoute: typeof DecksDeckIdListenRouteImport
      parentRoute: typeof DecksDeckIdRouteRoute
    }
    '/decks/$deckId/match': {
      id: '/decks/$deckId/match'
      path: '/match'
      fullPath: '/decks/$deckId/match'
      preLoaderRoute: typeof DecksDeckIdMatchRouteImport
      parentRoute: typeof DecksDeckIdRouteRoute
    }
    '/decks/$deckId/quiz': {
      id: '/decks/$deckId/quiz'
      path: '/quiz'
      fullPath: '/decks/$deckId/quiz'
      preLoaderRoute: typeof DecksDeckIdQuizRouteImport
      parentRoute: typeof DecksDeckIdRouteRoute
    }
    '/decks/$deckId/sentence': {
      id: '/decks/$deckId/sentence'
      path: '/sentence'
      fullPath: '/decks/$deckId/sentence'
      preLoaderRoute: typeof DecksDeckIdSentenceRouteImport
      parentRoute: typeof DecksDeckIdRouteRoute
    }
  }
}

interface DecksDeckIdRouteRouteChildren {
  DecksDeckIdClozeRoute: typeof DecksDeckIdClozeRoute
  DecksDeckIdDictationRoute: typeof DecksDeckIdDictationRoute
  DecksDeckIdFlashcardRoute: typeof DecksDeckIdFlashcardRoute
  DecksDeckIdListenRoute: typeof DecksDeckIdListenRoute
  DecksDeckIdMatchRoute: typeof DecksDeckIdMatchRoute
  DecksDeckIdQuizRoute: typeof DecksDeckIdQuizRoute
  DecksDeckIdSentenceRoute: typeof DecksDeckIdSentenceRoute
  DecksDeckIdIndexRoute: typeof DecksDeckIdIndexRoute
}

const DecksDeckIdRouteRouteChildren: DecksDeckIdRouteRouteChildren = {
  DecksDeckIdClozeRoute: DecksDeckIdClozeRoute,
  DecksDeckIdDictationRoute: DecksDeckIdDictationRoute,
  DecksDeckIdFlashcardRoute: DecksDeckIdFlashcardRoute,
  DecksDeckIdListenRoute: DecksDeckIdListenRoute,
  DecksDeckIdMatchRoute: DecksDeckIdMatchRoute,
  DecksDeckIdQuizRoute: DecksDeckIdQuizRoute,
  DecksDeckIdSentenceRoute: DecksDeckIdSentenceRoute,
  DecksDeckIdIndexRoute: DecksDeckIdIndexRoute,
}

const DecksDeckIdRouteRouteWithChildren =
  DecksDeckIdRouteRoute._addFileChildren(DecksDeckIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityRoute: CommunityRoute,
  DocsRoute: DocsRoute,
  IdiomsRoute: IdiomsRoute,
  LeaderboardRoute: LeaderboardRoute,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
  DecksDeckIdRouteRoute: DecksDeckIdRouteRouteWithChildren,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  GamesGameIdRoute: GamesGameIdRoute,
  GrammarTopicIdRoute: GrammarTopicIdRoute,
  PlayCodeRoute: PlayCodeRoute,
  SentencesPackIdRoute: SentencesPackIdRoute,
  TalkDialogueIdRoute: TalkDialogueIdRoute,
  GamesIndexRoute: GamesIndexRoute,
  GrammarIndexRoute: GrammarIndexRoute,
  PlayIndexRoute: PlayIndexRoute,
  SentencesIndexRoute: SentencesIndexRoute,
  TalkIndexRoute: TalkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
